[app]
# The name of your app as displayed in the menu
name = "Particles Eye"

# The submenu where your app should appear
menu = "Badge"

[entry]
# The name of your entry point `Application` class
class = "ParticlesEye"

[metadata]
# Your nickname.  Must be at most 32 characters!
author = "turiphro"

# License of your app as an SPDX identifier: <https://spdx.org/licenses/>
license = "Apache-2.0"

# URL to the repository of your app.
url = "https://git.flow3r.garden/turiphro/particles-eye"

# Description of your app.  Maximum 140 characters!
description = "Evil'ish eye formed by many flying particles. In spirit of both HAL 9000 and Sauron's Eye"

# Version number of your app.  If you push a commit where this number is
# increased, we interpret this as a new version being released.
#
# Version number must be an integer!
version = 1

